/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "add.h"

int *
add_1_svc(numbers *argp, struct svc_req *rqstp)
{
	static int  result;

	printf("La procedure distante d'addition est appele \n");
	result = argp->nbr1 + argp->nbr2;
	printf("%d + %d = %d \n", argp->nbr1, argp->nbr2, result);

	return &result;
}
