/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _SQRT_H_RPCGEN
#define _SQRT_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct number {
	float x;
};
typedef struct number number;

#define SQRT_PROG 0x20000002
#define SQRT_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define SQRT 1
extern  float * sqrt_1(number *, CLIENT *);
extern  float * sqrt_1_svc(number *, struct svc_req *);
extern int sqrt_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define SQRT 1
extern  float * sqrt_1();
extern  float * sqrt_1_svc();
extern int sqrt_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_number (XDR *, number*);

#else /* K&R C */
extern bool_t xdr_number ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_SQRT_H_RPCGEN */
