/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "sqrt.h"
#include <math.h>

float *ksqrt_1_svc(float *argp, struct svc_req *rqstp) {
    static float result;
    if (*argp < 0) {
        result = -1; 
    } else {
        result = sqrt(*argp);
    }
    return &result;
}
